/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721BurnEnum } from "./ERC721BurnEnum";
export * as factories from "./factories";
export { ERC721BurnEnum__factory } from "./factories/ERC721BurnEnum__factory";
