/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ProductFactory__factory } from "./ProductFactory__factory";
export { Erc20__factory } from "./Erc20__factory";
