/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Burn } from "./ERC20Burn";
export * as factories from "./factories";
export { ERC20Burn__factory } from "./factories/ERC20Burn__factory";
