/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721Burn } from "./ERC721Burn";
export * as factories from "./factories";
export { ERC721Burn__factory } from "./factories/ERC721Burn__factory";
