/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Common } from "./ERC20Common";
export * as factories from "./factories";
export { ERC20Common__factory } from "./factories/ERC20Common__factory";
