export { default as BaseDeployForm } from '@/modules/forms/BaseDeployForm.vue'
export { default as BaseEditForm } from '@/modules/forms/BaseEditForm.vue'
export { default as ProductInteractionForm } from '@/modules/forms/ProductInteractionForm.vue'
export { default as UpgradeToForm } from '@/modules/forms/UpgradeToForm.vue'
export { default as TransferOwnershipForm } from '@/modules/forms/TransferOwnershipForm.vue'
