{{- if .Values.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template.fullname" . }}-config
  labels:
    {{- include "template.labels" . | nindent 4 }}
data:
  {{ .Values.config.name  }}: |
                              document.ENV = {
                                VITE_ENVIRONMENT: 'development',
                                VITE_API_URL: 'http://localhost:8000/_/api/',
                                VITE_APP_APP_NAME: 'Dapppad On-Chain',
                                VITE_APP_AVAILABLE_CHAINS: [
                                  '5'
                                ],
                                VITE_APP_RPC_URL: {
                                  '5': 'https://goerli.infura.io/v3/'
                                },
                                VITE_APP_CONTRACTS: {
                                  '5': {
                                    'dapp': '0x353C50AB9E10b62D75aD057327acdB39C0dB8a0B',
                                    'farming': '0xDda6906636F681853665Ae155C9771119D51AdF4',
                                    'product-factory': '0xa5af85f98066DA249997d41E6233Aa82D3e3c9bc',
                                  },
                                },
                                VITE_APP_PRODUCT_ALIASES: {
                                  'erc20-base': '0x8ae85d849167ff996c04040c44924fd364217285e4cad818292c7ac37c0a345b',
                                  'erc721-base': '0x73ad2146b3d3a286642c794379d750360a2d53a3459a11b3e5d6cc900f55f44a',
                                },
                              }
{{- end }}
